import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import SessionProviderWrapper from '@/components/SessionProviderWrapper';
import ApolloProviderWrapper from '@/components/ApolloProviderWrapper';
import { GlobalStateProvider } from './context/GlobalStateContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-sunThin via-sunMedium to-sunStrong dark:from-moonThin dark:via-moonMedium dark:to-moonStrong`}
      >
        <GlobalStateProvider>
          <ApolloProviderWrapper>
            <SessionProviderWrapper>{children}</SessionProviderWrapper>
          </ApolloProviderWrapper>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
